### ISSUE TITLE
Create relaton-data-nist release archive that can be downloadable from official repo

### ISSUE THREAD

**Issue by ronaldtse** [relaton/NIST-Tech-Pubs#1]
We want to contribute a PR to the official repository that produces a Relaton YAML dataset that can be downloaded as a release asset.

The purpose is similar to that with BibTeX at https://github.com/usnistgov/NIST-Tech-Pubs/pull/32

This same workflow is already being used by IETF, and it would make lives much easier if this data set can be directly published by the authority (which avoids time synchronicity problems):
* https://github.com/ietf-tools/relaton-data-nist

We can re-use the GitHub Actions workflow:
https://github.com/relaton/relaton-data-nist/blob/main/.github/workflows/fetcher.yml

With the only change to the "relaton fetch" line where we input the XML file path directly.

**Comment by andrew2net** [comment]
@ronaldtse as I understand we need to generate YAML files with all the NIST documents and create GH artifact with the documents, right?
I have a couple questions:
- NIST uses the `allrecords-MODS.xml` and `pubs-export.json` data sources. Should we use both datasets?
- This repo contains outdated `allrecords.xml`, so we can't use it anymore. Maybe we should create the GH artifact in relation-data-nist, shouldn't we?

**Comment by ronaldtse** [comment]
This repo is just a fork so we can create the GHA to contribute, so it needs to be updated. 

We should only use allrecords-MODS.xml to generate the Relaton dataset. 

The GHA artifact for this repo is for NIST, it is different from our own Relaton dataset.

**Comment by ronaldtse** [comment]
So actually we shouldn't call it Relaton-data-nist, maybe just allrecords-relaton.yaml.

**Comment by andrew2net** [comment]
@ronaldtse should it be one YAML file with all the documents?

**Comment by ronaldtse** [comment]
Good point... Perhaps one file per document works better.

**Comment by andrew2net** [comment]
@ronaldtse I don't have permission to push to this repo
```sh
$ git push 
remote: Permission to relaton/NIST-Tech-Pubs.git denied to andrew2net.
fatal: unable to access 'https://github.com/relaton/NIST-Tech-Pubs.git/': The requested URL returned error: 403
```
Can you give me the permission or should I create a fork?

**Comment by ronaldtse** [comment]
@andrew2net sorry fixed now!

**Comment by andrew2net** [comment]
The dataset can be downloaded from the action running page https://github.com/relaton/NIST-Tech-Pubs/actions/runs/10617914201
